services:
  postgres:
    image: postgres:15-alpine
    container_name: etfpac-postgres
    environment:
      POSTGRES_DB: etfpac_db
      POSTGRES_USER: etfpac_user
      POSTGRES_PASSWORD: etfpac_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - etfpac-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etfpac_user -d etfpac_db"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build:
      context: .
      dockerfile: docker/docker/Dockerfile
    container_name: etfpac-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etfpac_db
      DB_USERNAME: etfpac_user
      DB_PASSWORD: etfpac_password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - etfpac-network
    volumes:
      - app_logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  app_logs:

networks:
  etfpac-network:
    driver: bridge

